name: CI
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Start SSH session
      uses: jessehouwing/debug-via-ssh@main
      with:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        SSH_PASS: ${{ secrets.SSH_PASS }}
        NGROK_REGION: eu
        NGROK_TIMEOUT: 150
        RUN_POST: false
    - run: |
        $time = Get-Date
        while ((Get-Date) -lt ($time).AddSeconds(45))
        {
            New-Guid
        }
      shell: pwsh
